---
# Le but de cette boucle est d'ajouter les certificats+key dans le keystore
# On le fait dans le format PKCS12 plutôt que JKS par défaut du fait de ce Warning de keytool:
#    Le fichier de clés JKS utilise un format propriétaire.
#    Il est recommandé de migrer vers PKCS12, qui est un format standard de l'industrie en utilisant [...]
# Le module ansible java_cert etc ne sait pas encore importer le PKCS12, ce qui oblige à passer d'abord par une commande openssl+keytool
# Évitez d'utiliser l'extension .pfx qui correspond à "l'ancêtre" du format .p12.

- name: set facilities vars from certificates_list
  set_fact:
    _ca_certificate: "{{ _certificate.ca_certificate }}" # ex: GandiStandardSSLCA2.pem
    _certificate_path: "{{ certificate_root_directory }}/{{ _certificate.name }}" # ex: /etc/ssl/mydomain.net

- name: Create temp PKCS12 keystore with openssl
  become: true
#  no_log: True
#  shell: "openssl pkcs12 -export -out {{ certificate_path }}/{{ tomcat_certificate_alias }}.pfx -inkey {{ certificate_path }}/{{ tomcat_certificate_alias }}.key -in {{ certificate_path }}/{{ tomcat_certificate_alias }}.crt -password pass:{{ keystore_pwd }}"
  ansible.builtin.command: >
      openssl pkcs12  -export
                      -in {{ _certificate_path }}/{{ _certificate.name }}.crt
                      -inkey {{ _certificate_path }}/{{ _certificate.name }}.key
                      -password pass:{{ _keystore_pwd }}
                      -out {{ _keystore_path }}/{{ _certificate.name }}.p12
                      {{ '-legacy' if ansible_os_family == 'RedHat' }}

- name: Create final PKCS12 keystore from temp p12 with keytool
  become: true
#  no_log: True
#  shell: "keytool -importkeystore -srckeystore {{ _keystore_path }}/{{ tomcat_certificate_alias }}.pfx -srcstoretype pkcs12 -srcalias 1 -srcstorepass {{ _keystore_pwd }} -destkeystore {{ _keystore_path }}/{{ _keystore_name }} -deststoretype jks -deststorepass {{ _keystore_pwd }} -destalias {{ tomcat_certificate_alias }}"
  ansible.builtin.command: >
      {{ java_home }}/bin/keytool -importkeystore -srckeystore {{ _keystore_path }}/{{ _certificate.name }}.p12
              -srcstoretype pkcs12 -srcalias 1 -srcstorepass '{{ _keystore_pwd }}'
              -destkeystore {{ _keystore_path }}/{{ _keystore_name }}
              -deststoretype pkcs12 -keyalg AES -keysize 128
              -deststorepass '{{ _keystore_pwd }}' -destalias {{ _certificate.name }}


- name: Import CA trust cert in keystore with keytool
  become: true
  ansible.builtin.java_cert:
    cert_alias: "{{ _ca_certificate }}"
    cert_path: "{{ _certificate_path }}/{{ _ca_certificate }}" # Local path to load certificate from (ex: GandiStandardSSLCA2.pem)
    keystore_path: "{{ _keystore_path }}/{{ _keystore_name }}" # Path to dest keystore. (ici: {{ tomcat_instance_name }}.keystore)
    keystore_pass: "{{ _keystore_pwd }}" # obligatoire mais inutile .. :/
    state: present

- name: Delete temp PKCS12 keystore
  become: true
  ansible.builtin.file:
    path: "{{ _keystore_path }}/{{ _certificate.name }}.p12"
    state: absent
